
services:
  - type: web
    name: djshop-rigenerato
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SITE_URL
        sync: false
      - key: UPLOADS_BUCKET
        value: uploads
      - key: ADMIN_ROLE_NAME
        value: admin
