services:
  - type: web
    name: djshoprigenerato
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SESSION_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        value: uploads
